config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root controller: :articles, action: :index
  resources :articles, only: [:index, :show, :new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates_presence_of :title, :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(params.require(:article).permit(:title, :content))
    if @article.persisted?
      redirect_to root_path, notice: 'Article succesfully created'
    else
      redirect_to new_article_path, notice: 'Error, try again'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(params.require(:article).permit(:title, :content))
      redirect_to root_path, notice: 'Your article has been successfully updated'
    else
      redirect_to edit_article_path, notice: 'Nope! try harder'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<%= form_with model: @article, local: true do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :content %>
  <%= form.text_area :content %>
  <%= form.submit 'Update Article' %>
<% end %>

app/views/articles/index.html.erb
<h1>GO ahead and create your own articles!</h1>
<h1>Crea tus Propios artículos!</h1>
<%= link_to 'Login', new_user_session_path %>


<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article) %><br />
    </li>
  <% end %>  
</ul>

<%= link_to 'Write Article - CREÁ TU ARTÍCULO', new_article_path %>

app/views/articles/new.html.erb
<%= form_with model: @article, local: true do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :content %>
  <%= form.text_area :content %>
  <%= form.submit 'Create Article' %>
<% end %>

app/views/articles/show.html.erb
<p><%= @article.title %></p>
<p><%= @article.content %></p>

<%= link_to 'Edit Article', edit_article_path %>
<button><%= link_to 'Back', root_path %><button/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
    <%= yield %>
  </body>
</html>